apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: processor
  name: processor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: processor
    spec:
      containers:
      - env:
        - name: AMQP_ADDRESS
          value: processing-queue
        - name: LIBRARY
          value: http://library:8000
        - name: STORE
          value: http://store:8000
        image: schanirs/processor
        name: processor
        resources: {}
      restartPolicy: Always
status: {}
