apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: processing-queue
  name: processing-queue
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: processing-queue
    spec:
      containers:
      - image: rabbitmq:3-management
        name: processing-queue
        ports:
        - containerPort: 15672
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: processing-queue-storage
      restartPolicy: Always
      volumes:
      - name: processing-queue-storage
        persistentVolumeClaim:
          claimName: processing-queue-storage
status: {}
