apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: store
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: CMDBEHZNRIW1UA6AQ80W
        - name: AWS_SECRET_ACCESS_KEY
          value: 9Wh/pknTtRVTzwyBo3HCdCXVYusegHWcBjT4g6cR
        - name: MINIO_ACCESS_KEY
          value: CMDBEHZNRIW1UA6AQ80W
        - name: MINIO_SECRET_KEY
          value: 9Wh/pknTtRVTzwyBo3HCdCXVYusegHWcBjT4g6cR
        - name: ROCKET_ADDRESS
          value: 0.0.0.0
        - name: STORAGE_HOST
          value: http://store_s3:9000
        image: schanirs/store
        name: store
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
