apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: thumbnailer
  name: thumbnailer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: thumbnailer
    spec:
      containers:
      containers:
      - env:
        - name: STORE_URL
          value: http://store:8000
        image: schanirs/thumbnailer:latest
        name: thumbnailer
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
